/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package testmodule/src */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h> /* for ptrdiff_t below */

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "rego_sdk_api.go"
#include <stdlib.h>
 typedef void (*evaluate_cb)(char*);
 void callEvaluateCallback(char* rs, evaluate_cb cb);
 typedef void (*pointer_cb)(int, char*);
 void callPointerCallback(int pointer, char* err, pointer_cb cb);

#line 1 "cgo-generated-wrapper"

#line 3 "store_sdk_api.go"
#include <stdlib.h>
 typedef void (*transaction_cb)(int, char*);
 void callTransactionCallback(int transactionId, char* err, transaction_cb cb);
 typedef void (*error_cb)(char*);
 void callErrorCallback(char* err, error_cb cb);

#line 1 "cgo-generated-wrapper"

#line 3 "string_sdk_api.go"
#include <stdlib.h>

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef __SIZE_TYPE__ GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern void RemoveCompiler(GoInt compilerId);
extern int CompileModules(char* modules);
extern int GetModules(int compilerId);
extern void Evaluate(GoInt compilerId, char* query, char* input, evaluate_cb callback);
extern void Partial(GoInt compilerId, char* query, char* input, evaluate_cb callback);
extern int PreparePartial(GoInt compilerId, GoInt storeId, char* query);
extern void RemovePartialQuery(GoInt partialQueryId);
extern int PreparedPartial(GoInt partialId, char* input, char** unknowns, int unknownsLength);
extern GoInt NewStore();
extern void RemoveStore(GoInt storeId);
extern void WriteToStore(int storeId, int transactionId, char* path, char* input);
extern int NewTransaction(int storeId);
extern void RemoveTransaction(int transactionId);
extern int CommitTransaction(int storeId, int transactionId);
extern GoInt UpsertPolicy(int storeId, int transactionId, char* policyName, char* module, error_cb callback);
extern void FreeString(int index);
extern char* GetString(int index);

#ifdef __cplusplus
}
#endif
