name: .NET

on:
  push:
    branches: [ main ]
    paths-ignore:
    - 'README.md'
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Build OSX Native
      run: build_native_osx.ps1
      if: ${{ matrix.os == 'macos-latest' }}
    - name: Restore dependencies
      run: dotnet restore
      working-directory: netcore
    - name: Build
      run: dotnet build --no-restore
      working-directory: netcore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: netcore
