name: Release

on:
  push:
    tags:
      - v*

jobs:
  publishNuget:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Extract tag name
      id: tag
      run: echo ::set-output name=VERSION::$(echo ${GITHUB_REF##*/v})
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Setup .NET Core 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Update project version
      uses: roryprimrose/set-vs-sdk-project-version@v1
      with:
        version: ${{ steps.tag.outputs.VERSION }}
    - name: Package core
      run: dotnet pack -c Release -o . netcore/src/OPADotNet.Core/OPADotNet.Core.csproj
    - name: Package embedded
      run: dotnet pack -c Release -o . netcore/src/OPADotNet.Embedded/OPADotNet.Embedded.csproj
    - name: Package expressions
      run: dotnet pack -c Release -o . netcore/src/OPADotNet.Expressions/OPADotNet.Expressions.csproj
    - name: Package test framework
      run: dotnet pack -c Release -o . netcore/src/OPADotNet.TestFramework/OPADotNet.TestFramework.csproj
    - name: Package aspnetcore
      run: dotnet pack -c Release -o . netcore/src/OPADotNet.AspNetCore/OPADotNet.AspNetCore.csproj
    - name: Package automapper
      run: dotnet pack -c Release -o . netcore/src/OPADotNet.Automapper/OPADotNet.Automapper.csproj
    - name: Package reason
      run: dotnet pack -c Release -o . netcore/src/OPADotNet.Reasons/OPADotNet.Reasons.csproj
    - name: Publish
      run: dotnet nuget push *.nupkg -k ${{ secrets.NUGET_KEY }} -s https://api.nuget.org/v3/index.json
    
    
